class StrategiesSetup():

	RSI_OverSold = 'RSI_OverSold'
	
	config = {

		# Defaults: 'ltf_interval' : "5m", 'rsi_period' : 5
		RSI_OverSold : [
			{'ticker': 'AAPL', 'rsi_period' : 2, 'rsi_limit': 15, 'tp_percentage': 4 },
			{'ticker': 'ADBE', 'rsi_period' : 5, 'rsi_limit': 20, 'tp_percentage': 3 },
			{'ticker': 'AMD', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 15 },
			{'ticker': 'AMZN', 'rsi_period' : 2, 'rsi_limit': 30, 'tp_percentage': 5 },
			{'ticker': 'ANSS', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 2 },
			{'ticker': 'BABA', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 3 },
			{'ticker': 'BBBY', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 4 },
			{'ticker': 'BLDR', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 15 },
			{'ticker': 'BYD', 'rsi_period' : 9, 'rsi_limit': 30, 'tp_percentage': 2 },
			{'ticker': 'BYND', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 4 },
			{'ticker': 'CHTR', 'rsi_period' : 9, 'rsi_limit': 25, 'tp_percentage': 6 },
			{'ticker': 'CHWY', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 6 },
			{'ticker': 'COUP', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 10 },
			{'ticker': 'CRL', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 5 },
			{'ticker': 'CRM', 'rsi_period' : 5, 'rsi_limit': 20, 'tp_percentage': 5 },
			{'ticker': 'CROX', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 4 },
			{'ticker': 'CRWD', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 4 },
			{'ticker': 'CSIQ', 'rsi_period' : 2, 'rsi_limit': 15, 'tp_percentage': 3 },
			{'ticker': 'CTAS', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 7 },
			{'ticker': 'CVNA', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 25 },
			{'ticker': 'CZR', 'rsi_period' : 14, 'rsi_limit': 25, 'tp_percentage': 25 },
			{'ticker': 'DAL', 'rsi_period' : 5, 'rsi_limit': 5, 'tp_percentage': 5 },
			{'ticker': 'DAR', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 10 },
			{'ticker': 'DELL', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 2 },
			{'ticker': 'DHI', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 5 },
			{'ticker': 'DHR', 'rsi_period' : 9, 'rsi_limit': 25, 'tp_percentage': 4 },
			{'ticker': 'DKS', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 6 },
			{'ticker': 'DOCU', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 2 },	
			{'ticker': 'DOYU', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 2 },	
			{'ticker': 'DPZ', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 2 },	
			{'ticker': 'DRI', 'rsi_period' : 5, 'rsi_limit': 5, 'tp_percentage': 10 },	
			{'ticker': 'EDU', 'rsi_period' : 5, 'rsi_limit': 10, 'tp_percentage': 7 },	
			{'ticker': 'ENPH', 'rsi_period' : 2, 'rsi_limit': 25, 'tp_percentage': 10 },	
			{'ticker': 'ETSY', 'rsi_period' : 2, 'rsi_limit': 10, 'tp_percentage': 5 },	
			{'ticker': 'FAST', 'rsi_period' : 2, 'rsi_limit': 10, 'tp_percentage': 1 },	
			{'ticker': 'FBHS', 'rsi_period' : 9, 'rsi_limit': 30, 'tp_percentage': 7 },	
			{'ticker': 'FCX', 'rsi_period' : 9, 'rsi_limit': 25, 'tp_percentage': 5 },	
			{'ticker': 'FDX', 'rsi_period' : 9, 'rsi_limit': 20, 'tp_percentage': 7 },	
			{'ticker': 'FRPT', 'rsi_period' : 14, 'rsi_limit': 25, 'tp_percentage': 4 },	
			{'ticker': 'FSLY', 'rsi_period' : 2, 'rsi_limit': 10, 'tp_percentage': 6 },
			{'ticker': 'FVRR', 'rsi_period' : 2, 'rsi_limit': 20, 'tp_percentage': 4 },	
			{'ticker': 'GME', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 7 },
			{'ticker': 'GNRC', 'rsi_period' : 9, 'rsi_limit': 20, 'tp_percentage': 7 },	
			{'ticker': 'GPI', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 7 },	
			{'ticker': 'GPS', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 15 },	
			{'ticker': 'HD', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 4 },	
			{'ticker': 'HUBS', 'rsi_period' : 9, 'rsi_limit': 20, 'tp_percentage': 10 },	
			{'ticker': 'IBP', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 25 },	
			{'ticker': 'IDXX', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 4 },	
			{'ticker': 'INFY', 'rsi_period' : 5, 'rsi_limit': 20, 'tp_percentage': 2 },	
			{'ticker': 'INSP', 'rsi_period' : 5, 'rsi_limit': 10, 'tp_percentage': 10 },	
			{'ticker': 'IPHI', 'rsi_period' : 5, 'rsi_limit': 10, 'tp_percentage': 7 },	
			{'ticker': 'IRTC', 'rsi_period' : 5, 'rsi_limit': 5, 'tp_percentage': 1 },	
			{'ticker': 'JD', 'rsi_period' : 9, 'rsi_limit': 30, 'tp_percentage': 5 },	
			{'ticker': 'LAD', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 3 },	
			{'ticker': 'LEN', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 2 },	
			{'ticker': 'LOW', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 3 },	
			{'ticker': 'LULU', 'rsi_period' : 2, 'rsi_limit': 10, 'tp_percentage': 3 },	
			{'ticker': 'MDB', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 15 },	
			{'ticker': 'MELI', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 10 },	
			{'ticker': 'MRNA', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 15 },	
			{'ticker': 'MRTX', 'rsi_period' : 9, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'MRVL', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 6 },	
			{'ticker': 'MSCI', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 1 },	
			{'ticker': 'MTCH', 'rsi_period' : 5, 'rsi_limit': 14, 'tp_percentage': 4 },	
			{'ticker': 'MTH', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 10 },	
			{'ticker': 'NIO', 'rsi_period' : 2, 'rsi_limit': 10, 'tp_percentage': 15 },	# Manual TP
			{'ticker': 'NIU', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 15 },	# Manual TP
			{'ticker': 'NKE', 'rsi_period' : 14, 'rsi_limit': 20, 'tp_percentage': 3 },	
			{'ticker': 'NOW', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 3 },	
			{'ticker': 'NUAN', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 5 },	
			{'ticker': 'NVCR', 'rsi_period' : 9, 'rsi_limit': 10, 'tp_percentage': 2 },	
			{'ticker': 'NVDA', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 10 },	
			{'ticker': 'NXPI', 'rsi_period' : 25, 'rsi_limit': 25, 'tp_percentage': 5 },	
			{'ticker': 'OMI', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 3 },	
			{'ticker': 'PAYC', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 3 },	
			{'ticker': 'PDD', 'rsi_period' : 9, 'rsi_limit': 20, 'tp_percentage': 7 },	
			{'ticker': 'PG', 'rsi_period' : 25, 'rsi_limit': 25, 'tp_percentage': 1 },	
			{'ticker': 'PINS', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 10 },	
			{'ticker': 'PKI', 'rsi_period' : 9, 'rsi_limit': 30, 'tp_percentage': 4 },	
			{'ticker': 'PODD', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 1 },	
			{'ticker': 'POOL', 'rsi_period' : 5, 'rsi_limit': 5, 'tp_percentage': 5 },	
			{'ticker': 'POWI', 'rsi_period' : 14, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'PTON', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 10 },	
			{'ticker': 'PYPL', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 6 },	
			{'ticker': 'RGEN', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 3 },	
			{'ticker': 'RH', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'ROKU', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 7 },	
			{'ticker': 'RS', 'rsi_period' : 9, 'rsi_limit': 20, 'tp_percentage': 2 },	
			{'ticker': 'SAIL', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 2 },	
			{'ticker': 'SE', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 3 },	
			{'ticker': 'SGEN', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 5 },	
			{'ticker': 'SHOP', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 5 },	
			{'ticker': 'SNAP', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'SNOW', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 4 },	
			{'ticker': 'SPWR', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 10 },	
			{'ticker': 'SQ', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 1 },	
			{'ticker': 'STMP', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'STNE', 'rsi_period' : 14, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'TGT', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 1 },	
			{'ticker': 'TMO', 'rsi_period' : 14, 'rsi_limit': 20, 'tp_percentage': 2 },	
			{'ticker': 'TOL', 'rsi_period' : 5, 'rsi_limit': 30, 'tp_percentage': 5 },	
			{'ticker': 'TREX', 'rsi_period' : 14, 'rsi_limit': 30, 'tp_percentage': 7 },	
			{'ticker': 'TSLA', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 4 },	
			{'ticker': 'TTD', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 7 },	
			{'ticker': 'TWLO', 'rsi_period' : 2, 'rsi_limit': 15, 'tp_percentage': 5 },	
			{'ticker': 'TWTR', 'rsi_period' : 5, 'rsi_limit': 15, 'tp_percentage': 3 },	
			{'ticker': 'UPS', 'rsi_period' : 2, 'rsi_limit': 5, 'tp_percentage': 1 },	
			{'ticker': 'VCYT', 'rsi_period' : 9, 'rsi_limit': 15, 'tp_percentage': 10 },	
			{'ticker': 'VEEV', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 10 },	
			{'ticker': 'W', 'rsi_period' : 5, 'rsi_limit': 20, 'tp_percentage': 10 },	
			{'ticker': 'WIX', 'rsi_period' : 5, 'rsi_limit': 25, 'tp_percentage': 5 },	
			{'ticker': 'Z', 'rsi_period' : 5, 'rsi_limit': 10, 'tp_percentage': 10 },	
			{'ticker': 'ZEN', 'rsi_period' : 14, 'rsi_limit': 25, 'tp_percentage': 6 },	
			{'ticker': 'ZM', 'rsi_period' : 14, 'rsi_limit': 20, 'tp_percentage': 25 }, #Update	
			{'ticker': 'ZNGA', 'rsi_period' : 14, 'rsi_limit': 20, 'tp_percentage': 1 },	
			{'ticker': 'ZTS', 'rsi_period' : 25, 'rsi_limit': 30, 'tp_percentage': 5 },	
		]
	}

